Rails.application.routes.draw do
  get 'producer', to: 'producer#index'
  get 'genre', to: 'genre#index'
  get 'get_dataproducer', to: 'producer#get_dataproducer' 
  get 'get_datagenre', to: 'genre#get_datagenre' 
  get '/:id/genre/edit', to: 'genre#edit', as: 'edit_genre'
  patch '/:id/genre/edit/update', to: 'genre#update', as: 'update_genre'  
  # delete '/:id/genre/delete', to: 'genre#destroy', as: 'delete_genre' 
  get '/:id/producer/edit', to: 'producer#edit', as: 'edit_producer'
  patch '/:id/producer/edit/update', to: 'producer#update', as: 'update_producer'  
  # delete '/:id/producer/delete', to: 'producer#destroy', as: 'delete_producer' 
  get 'add_producer', to: 'producer#new'   
  post 'add_producer', to: 'producer#create'  
  get 'add_genre', to: 'genre#new'   
  post 'add_genre', to: 'genre#create'  
  get '/:id/account/edit', to: 'session#edit', as: 'edit_account'
  patch '/:id/account/edit/update', to: 'session#update', as: 'update_account'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'sign_up', to: 'registration#new'
  post 'sign_up', to: 'registration#create'
  get 'sign_in', to: 'session#new'
  post 'sign_in', to: 'session#create', as: 'log_in'
  delete 'logout', to: 'session#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'      
  get 'get_datauser', to: 'session#get_datauser' 
  get 'get_datafilm',to: 'welcome#get_datafilm'
  get 'add_movie', to: 'welcome#new'   
  post 'add_movie', to: 'welcome#create'  
  get '/:id/edit', to: 'welcome#edit', as: 'edit_movie'
  patch '/:id/edit/update', to: 'welcome#update', as: 'update_movie'     
  delete '/:id/delete', to: 'welcome#destroy', as: 'delete_movie'                 
end
